### ISSUE TITLE
Issue while installing required dependencies 

### ISSUE THREAD

**Issue by Squidtoon99** [KadhirV/Eproctor#1]
There is a problem in the requirements.txt that makes installing this project impossible unless on the host computer. 

line 25 -
> PyAudio @ file:///C:/Kadhir/Mystuff/kadhir/Coding/Python/hackathons/Eproctor/venv/Scripts/PyAudio-0.2.11-cp39-cp39-win_amd64.whl

this references a file on @KadhirV 's windows based file system and will fail when you are trying to install it. 

I recommend either using the proper wheel location `PyAudio-0.2.11-cp39-cp39-win_amd64.whl` **or** containerizing this project and using a linus-based os with support for apt-get using proper portaudio deps.

**Comment by KadhirTheEngineer** [comment]
I just noticed. I generated a requirements.txt file and did not fully check over it. look at readme again and thank you for pointing it out.
